package com.cloudnest.file.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EntityListeners;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import java.time.LocalDateTime;

/**
 * Represents metadata for a file stored in the CloudNest platform.
 * <p>
 * This entity manages file metadata only — the actual binary content is
 * stored externally (local disk, S3, MinIO, etc.) and integrated in a later phase.
 * Supports soft-delete via the {@code status} field.
 */
@Entity
@Table(name = "file_metadata")
@EntityListeners(AuditingEntityListener.class)
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class FileMetadata {

    /**
     * Internal auto-generated primary key.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Public-facing unique file identifier (UUID).
     * Used in API responses and external references.
     */
    @Column(name = "file_id", nullable = false, unique = true, updatable = false, length = 36)
    private String fileId;

    /**
     * Original file name as provided by the user at upload time.
     */
    @Column(name = "original_file_name", nullable = false, length = 255)
    private String originalFileName;

    /**
     * Name under which the file is stored on the storage backend.
     * Generated by the system to avoid collisions.
     */
    @Column(name = "stored_file_name", nullable = false, unique = true, length = 255)
    private String storedFileName;

    /**
     * MIME type or file extension category (e.g. "image/png", "application/pdf").
     */
    @Column(name = "file_type", nullable = false, length = 100)
    private String fileType;

    /**
     * File size in bytes.
     */
    @Column(name = "file_size", nullable = false)
    private Long fileSize;

    /**
     * Storage path relative to the storage backend root.
     */
    @Column(name = "storage_path", nullable = false, length = 512)
    private String storagePath;

    /**
     * ID of the user who owns this file.
     */
    @Column(name = "owner_id", nullable = false)
    private Long ownerId;

    /**
     * ID of the folder this file belongs to (nullable for root-level files).
     */
    @Column(name = "folder_id")
    private Long folderId;

    /**
     * Whether this file is publicly accessible without authentication.
     */
    @Column(name = "is_public", nullable = false)
    @Builder.Default
    private Boolean isPublic = false;

    /**
     * Checksum (e.g. MD5, SHA-256) for integrity verification.
     */
    @Column(name = "checksum", length = 64)
    private String checksum;

    /**
     * Current lifecycle status of the file.
     * <ul>
     *   <li>{@code ACTIVE} — file is available for access</li>
     *   <li>{@code DELETED} — file has been soft-deleted</li>
     * </ul>
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false, length = 20)
    @Builder.Default
    private FileStatus status = FileStatus.ACTIVE;

    /**
     * Timestamp when the file metadata record was created.
     * Managed automatically by JPA auditing.
     */
    @CreatedDate
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    /**
     * Timestamp when the file metadata record was last updated.
     * Managed automatically by JPA auditing.
     */
    @LastModifiedDate
    @Column(name = "updated_at", nullable = false)
    private LocalDateTime updatedAt;

    /**
     * Enum representing the lifecycle status of a file record.
     */
    public enum FileStatus {
        ACTIVE,
        DELETED
    }
}
